# Generate the SCP Policy
resource "aws_organizations_policy" "scp_document" {
  name        = local.name
  description = "${local.name} : SCP generated by org-scp module"
  content     = data.aws_iam_policy_document.scp_policy.json
  tags        = local.tags
}

# Create the attachment for the targets
resource "aws_organizations_policy_attachment" "scp_attachment" {
  for_each  = var.targets
  policy_id = aws_organizations_policy.scp_document.id
  target_id = each.value
}

data "aws_organizations_organization" "org" {}

data "aws_organizations_organizational_units" "root" {
  parent_id = data.aws_organizations_organization.org.roots[0].id

}

data "aws_organizations_organizational_units" "sub_ous" {
  parent_id = data.aws_organizations_organizational_units.root.children[0].id

}