apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: myapp
    type: front-end
  name: myapp-replicaset
spec:
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
      name: myapp-pod
    spec:
      containers:
      - image: nginx
        name: nginx-container
  replicas: 3
  selector:
    matchLabels: 
      app: myapp
      type: front-end


