apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
# To have the volume on the node  
  hostPath:
    path: /tmp/data

# or to have the volume on aws ebs

  awsElasticBlockStore:
    volumeID: vol-0c9f7d5b9b5d5b9b
    fsType: ext4