apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ebs-sc # or gcp-storage
  resources: 
    requests:
      storage: 500Mi