apiVersion: v1
kind: Pod
metadata:
  labels:
    name: simple-webapp
  name: simple-webapp
spec:
  containers:
  - image: simple-webapp
    name: simple-webapp
    ports: 
      - containerPort: 8080
  - image: log-agent
    name: log-agent

    